spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: ${SUPABASE_DB_PASSWORD}
    url: jdbc:postgresql:postgres://db.aagdzusmeniqghpykyxs.supabase.co:5432/postgres
  jpa:
    hibernate:
      ddl-auto: update
  cloud:
    config:
      enabled: false